- name: Configure Login Banner on Cisco Routers
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Set login banner
      ios_banner:
        banner: "{{ banner_type }}"
        text: "{{ banner_text }}"
        state: "{{ 'present' if enable_banner == 'yes' else 'absent' }}"

    - name: Verify banner configuration
      ios_command:
        commands:
          - show running-config | include banner
      register: banner_output

    - name: Display banner configuration
      debug:
        var: banner_output.stdout_lines
